### ISSUE TITLE
Browser can't seem to show changes 

### ISSUE THREAD

**Issue by Marini83** [weisuke/react-reflux-go-boilerplate#1]
Hello,

I would like to thank you for this fantastic boilerplate you guys have put together. I am a total newb and was trying to change the header index.jsx file, which I did but the browser doesn't show  any of the changes?  Not sure what's going on?

**Comment by weisuke** [comment]
Hi, sorry for the late response, I haven't looked at this in a while and I don't have the plan to maintain this, maybe some of the dependencies are not up to date. I'm planning to put together another boilerplate with react + redux with newer dependencies
